[package]
name = "BackTester"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.9", features = ["json"] }
serde_json = "1.0.132"
chrono = "0.4.38"
chrono-tz = "0.10.1"